# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'documentReader.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(674, 367)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 602, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(6, 6))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FileToOpen = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.FileToOpen.setObjectName("FileToOpen")
        self.horizontalLayout.addWidget(self.FileToOpen)
        self.OpenFile = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.OpenFile.setMinimumSize(QtCore.QSize(80, 40))
        self.OpenFile.setMaximumSize(QtCore.QSize(80, 40))
        self.OpenFile.setBaseSize(QtCore.QSize(20, 12))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.OpenFile.setFont(font)
        self.OpenFile.setDefault(True)
        self.OpenFile.setFlat(False)
        self.OpenFile.setObjectName("OpenFile")
        self.horizontalLayout.addWidget(self.OpenFile)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.HttpAddress = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.HttpAddress.setObjectName("HttpAddress")
        self.horizontalLayout_4.addWidget(self.HttpAddress)
        self.WriteWebFile = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.WriteWebFile.setMinimumSize(QtCore.QSize(80, 40))
        self.WriteWebFile.setMaximumSize(QtCore.QSize(80, 40))
        self.WriteWebFile.setBaseSize(QtCore.QSize(20, 12))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.WriteWebFile.setFont(font)
        self.WriteWebFile.setAutoDefault(False)
        self.WriteWebFile.setDefault(True)
        self.WriteWebFile.setObjectName("WriteWebFile")
        self.horizontalLayout_4.addWidget(self.WriteWebFile)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.Sound = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.Sound.setObjectName("Sound")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Sound)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.PlaySound = QtWidgets.QPushButton(self.Sound)
        self.PlaySound.setMinimumSize(QtCore.QSize(80, 40))
        self.PlaySound.setMaximumSize(QtCore.QSize(80, 40))
        self.PlaySound.setBaseSize(QtCore.QSize(20, 12))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.PlaySound.setFont(font)
        self.PlaySound.setStyleSheet("QPushButton:hover {background-color: rgb(0, 0, 255); border:none; color: rgb(255,255,255);font: 75 14pt \"Times New Roman\";}")
        self.PlaySound.setDefault(True)
        self.PlaySound.setObjectName("PlaySound")
        self.gridLayout.addWidget(self.PlaySound, 2, 4, 1, 1)
        self.SoundFileName = QtWidgets.QLineEdit(self.Sound)
        self.SoundFileName.setObjectName("SoundFileName")
        self.gridLayout.addWidget(self.SoundFileName, 2, 1, 1, 3)
        self.pauseButton = QtWidgets.QPushButton(self.Sound)
        self.pauseButton.setMinimumSize(QtCore.QSize(80, 40))
        self.pauseButton.setMaximumSize(QtCore.QSize(80, 40))
        self.pauseButton.setBaseSize(QtCore.QSize(20, 12))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pauseButton.setFont(font)
        self.pauseButton.setCheckable(True)
        self.pauseButton.setChecked(False)
        self.pauseButton.setDefault(True)
        self.pauseButton.setObjectName("pauseButton")
        self.gridLayout.addWidget(self.pauseButton, 4, 1, 1, 1)
        self.playButton = QtWidgets.QPushButton(self.Sound)
        self.playButton.setMinimumSize(QtCore.QSize(80, 40))
        self.playButton.setMaximumSize(QtCore.QSize(80, 40))
        self.playButton.setBaseSize(QtCore.QSize(20, 12))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.playButton.setFont(font)
        self.playButton.setDefault(True)
        self.playButton.setObjectName("playButton")
        self.gridLayout.addWidget(self.playButton, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.Sound)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.stopButton = QtWidgets.QPushButton(self.Sound)
        self.stopButton.setMinimumSize(QtCore.QSize(80, 40))
        self.stopButton.setMaximumSize(QtCore.QSize(80, 40))
        self.stopButton.setBaseSize(QtCore.QSize(20, 12))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.stopButton.setFont(font)
        self.stopButton.setDefault(True)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout.addWidget(self.stopButton, 4, 3, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.Sound)
        self.OutputMessages = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OutputMessages.setFont(font)
        self.OutputMessages.setObjectName("OutputMessages")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.OutputMessages)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar{border: 1px solid blue; border-radius: 1px;text-align:center;font: 75 14pt \"Times New Roman\";color:black;}QProgressBar::chunk{background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:1, stop:0.159091 rgba(0, 226, 246, 255), stop:1 rgba(62, 75, 144, 255));width:20px;}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.progressBar)
        self.verticalLayout.addLayout(self.formLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 674, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionExit)
        self.menuMenu.addSeparator()
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.WriteWebFile.clicked.connect(self.HttpAddress.copy)
        self.OpenFile.clicked.connect(self.FileToOpen.copy)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Document Reader"))
        self.label.setText(_translate("MainWindow", "Document Reader"))
        self.label_2.setText(_translate("MainWindow", "File:"))
        self.OpenFile.setText(_translate("MainWindow", "Open"))
        self.label_3.setText(_translate("MainWindow", "Website:"))
        self.WriteWebFile.setText(_translate("MainWindow", "Open"))
        self.PlaySound.setText(_translate("MainWindow", "Create"))
        self.pauseButton.setText(_translate("MainWindow", "Pause"))
        self.playButton.setText(_translate("MainWindow", "Play"))
        self.label_4.setText(_translate("MainWindow", "Sound File:"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.OutputMessages.setText(_translate("MainWindow", "Document size determines processing time."))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))

